product/urls.py
from django.urls import path, re_path
from .views import  *

app_name = 'product'

urlpatterns = [
    # path("", HomeListView.as_view(), name="home"),
    path("", home, name="home"),
    path("products/", ProductListView.as_view(), name="products"),
    re_path(r"^product/(?P<slug>.*)/$", ProductDetailView.as_view(), name="productDetail"),
    path("Order-Summry/", OrderSummryView.as_view(), name="Order_Summry_View"),
    re_path(r"^add_to_cart/(?P<slug>.*)/$", add_to_cart, name="add_to_cart"),
    re_path(r"^remove-from-cart/(?P<slug>.*)/$", remove_from_cart, name="remove_from_cart"),
    re_path(r"^remove-signal-item-from-cart/(?P<slug>.*)/$", remove_signal_item_from_cart, name="remove_signal_item_from_cart"),
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace="Product")),
    path('ckeditor/', include('ckeditor_uploader.urls')),


] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.db.models.deletion import SET_NULL
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from slugify import  slugify_unicode
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User

class Customer(models.Model):
    user = models.OneToOneField(User, verbose_name="أسم المستخدم", on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    #device = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"

    def __str__(self):
        if self.user:
            name = str(self.user)
        else:
            name = self.device
        return str(name)
        
def image_upload(instance, filename):
    imageName, extension = filename.split('.')
    return "products/%s/%s/%s.%s"%(instance.ProBrand,instance.ProCtegory,instance.ProName ,extension)

class Product(models.Model): # the prodact is a main class 
    ProName = models.CharField(max_length=150, unique=True, verbose_name='اسم المنتج كامل')
    ProCtegory = models.ForeignKey("Category", on_delete=models.CASCADE, blank=True, null=True, verbose_name="نوع المنتج")
    ProBrand = models.ForeignKey('brands.Brand', related_name='Brands', on_delete=models.CASCADE, blank=True, null=True, verbose_name="الماركة")
    # ProAlternatve = 
    ProDesc = RichTextField(verbose_name="تفاصيل المنتج")
    ProStock = models.BooleanField(default=True, blank=True, null=True, verbose_name="المخزون")
    ProPrice = models.DecimalField(max_digits=6, decimal_places=0, verbose_name="سعر السوق")
    ProDiscountPrice = models.DecimalField(max_digits=6, decimal_places=0, verbose_name="السعر بعد الخصم", default=0, blank=True, null=True)
    ProImg_1 = models.ImageField(upload_to=image_upload, blank=True, null=True, default = '../static/assets/images/no-image.jpg', max_length=250, verbose_name='الصورة الرئيسية')
    ProImg_2 = models.ImageField(upload_to=image_upload, blank=True, null=True, default = '../static/assets/images/no-image.jpg', max_length=250, verbose_name='الصورة الفرعية')
    ProCreated = models.DateTimeField(auto_now=True)

    slug = models.SlugField(blank=True, null=True, verbose_name="URl")

    def save(self,*args, **kwargs):
        if not self.slug :
            self.slug = slugify_unicode(self.ProName, allow_unicode=True)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("Product:productDetail", kwargs={"slug": self.slug})
    
    def get_add_to_cart_url(self):
        return reverse("Product:add_to_cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse("Product:remove_from_cart", kwargs={"slug": self.slug})
    
    def get_category_url(self):
        return reverse("Product:products")

    def __str__(self):
        return self.ProName

        
class Category(models.Model):
    CatName = models.CharField(max_length=50, verbose_name = 'نوع المنتج')

    def __str__(self):
        return self.CatName

class OrderItem(models.Model):
    user = models.ForeignKey(User, verbose_name="أسم المستخدم", on_delete=SET_NULL, blank=True, null=True)
    item = models.ForeignKey(Product, related_name='order_item', on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)
    
    class Meta:
        verbose_name = "OrderItem"
        verbose_name_plural = "OrderItems"

    def __str__(self):
        return f"{self.quantity} of {self.item.ProName}"

    def totle_price_discount(self):
        return self.quantity * self.item.ProDiscountPrice
    
    def totle_price(self):
        return self.item.ProPrice * self.quantity

    def totle_saving_price(self):
        return self.totle_price() - self.totle_price_discount()

    def get_finla_price(self):
        if self.item.ProDiscountPrice:
            return self.totle_price_discount()
        return self.totle_price()

    def get_finla_price_saving(self):
        if self.item.ProDiscountPrice:
            return self.totle_saving_price()
        return 0
           

class Order(models.Model):
    """Model definition for Order."""
    OrdName = models.ForeignKey(User, verbose_name="أسم المستخدم", on_delete=SET_NULL, blank=True, null=True)
    items = models.ManyToManyField(OrderItem, verbose_name="المنتجات المطلوبة")
    OrdStartDate = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ اضافة المنتج")
    OrdOrderedDate = models.DateTimeField()
    OrdOrdered = models.BooleanField(default=False)

    class Meta:
        """Meta definition for Order."""

        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        """Unicode representation of Order."""
        return self.OrdName.user.username

    def get_total(self):
        total = 0
        for total_item in self.items.all():
            total += total_item.get_finla_price()
        return total

    def get_total_saving(self):
        total = 0
        for total_item in self.items.all():
            total += total_item.get_finla_price_saving()
        return total

###
##### Alternatve it may be opened in the future
###
# class ProductAlternative(models.Model):
#     PrAlName = models.ForeignKey(Product, related_name='choose_product', on_delete=models.CASCADE, verbose_name="المنتج")
#     PrAlternative = models.ManyToManyField(Product, related_name="product_with_alternative", verbose_name="بدائل المنتج")

#     class Meta:
#         verbose_name = "ProductAlternative"
#         verbose_name_plural = "ProductAlternatives"

#     def __str__(self):
#         return str(self.PrAlName)

product/forms.py
from django import forms
# from django.forms.models import ModelForm
from . models import Product

class ProductForm(forms.ModelForm):
    """Form definition for Product."""

    class Meta:
        """Meta definition for Productform."""

        model = Product
        fields = ('ProCtegory','ProBrand','ProBrand')

product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View, CreateView
from . models import *
from django.utils import timezone
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from . filters import ProductFilter
# from . forms import ProductForm

class ProductListView(ListView):
    model = Product
    paginate_by = 3
    template_name = "Product\product_list.html"

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['filter'] = ProductFilter(self.request.GET, queryset=self.get_queryset())
        return context

class ProductDetailView(DetailView):
    model = Product
    template_name = "Product\product_detail.html"

# class ProductCreateView(CreateView):
#     model = Product
#     template_name = "Product\product_list.html"



# class HomeListView(ListView):
#     queryset = Product.objects.filter(ProCtegory__icontains='screen')
#     template_name = "home.html"
def home(request):
    led = Product.objects.filter(ProCtegory__CatName='تليفزيونات LED')
    degetal = Product.objects.filter(ProCtegory__CatName='تليفزيونات ديچيتال')
    android = Product.objects.filter(ProCtegory__CatName='تليفزيونات اندرويد')
    smart = Product.objects.filter(ProCtegory__CatName='التليفزيونات الذكية')
    context = {'home':led, 'degetal':degetal, 'android':android, 'smart':smart}
    return render(request, 'Product/home.html', context)
    

class OrderSummryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(OrdName=self.request.user, OrdOrdered=False)
            context = {'object': order}
            return render(self.request, "Product\cart.html", context)
        except ObjectDoesNotExist:
            messages.error(self.request,'انت ليس لديك منتجات مختارة')
            return redirect('/')

def cart(request):
    order = Order.objects.get(OrdName=request.user, OrdOrdered=False)
    context = {'object': order}
    return render(request, "templates/base.html", context)
    
@login_required
def add_to_cart(request, slug):
    itemed = get_object_or_404(Product, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=itemed,
        user=request.user,
        ordered=False
        )
    order_qs = Order.objects.filter(
        OrdName=request.user,
         OrdOrdered=False
         )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=itemed.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.success(request, f"تم تحديث كمية")
            return redirect ("Product:Order_Summry_View")
        else:
            order.items.add(order_item)
            order.save()
            messages.success(request, f" تم اضافة المنتج الي العربة")
            return redirect ("Product:Order_Summry_View")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(OrdName=request.user, OrdOrderedDate=ordered_date)
        order.items.add(order_item)
        order.save()
        messages.success(request, f" تم اضافة المنتج الي العربة")
        return redirect ("Product:Order_Summry_View")

@login_required
def remove_from_cart(request, slug):
    itemed = get_object_or_404(Product, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=itemed,
        user=request.user,
        ordered=False
        )
    order_qs = Order.objects.filter(
        OrdName=request.user,
         OrdOrdered=False
         )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=itemed.slug).exists():
            order.items.remove(order_item)
            order_item.quantity = 1
            order_item.save()
            order.save()
            messages.success(request, f"اتمسحت من العربة التسوق")
            return redirect ("Product:Order_Summry_View")
        else:
            messages.info(request, f" غير موجود في العربة")
            return redirect ("Product:productDetail", slug=slug)
    else:
        messages.info(request, f" ليس لديك منتجات في العربة")
        return redirect ("Product:productDetail", slug=slug)


@login_required
def remove_signal_item_from_cart(request, slug):
    itemed = get_object_or_404(Product, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=itemed,
        user=request.user,
        ordered=False
        )
    order_qs = Order.objects.filter(
        OrdName=request.user,
         OrdOrdered=False
         )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=itemed.slug).exists():
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.success(request, f"اتمسحت من العربة التسوق")
            return redirect ("Product:Order_Summry_View")
        else:
            messages.info(request, f" غير موجود في العربة")
            return redirect ("Product:Order_Summry_View", slug=slug)
    else:
        messages.info(request, f" ليس لديك منتجات في العربة")
        return redirect ("Product:Order_Summry_View", slug=slug)

product/templates/product/cart.html
{% extends 'base.html' %}
{% block body %}
        <main class="main">
            <nav aria-label="breadcrumb" class="breadcrumb-nav">
                <div class="container">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'Product:products' %}" class="fs-3 fw-bold">الرئيسية</a></li> .
                        <li class="breadcrumb-item fs-3 fw-bold active" aria-current="page">سلة المشترايات</li>
                    </ol>
                </div>
            </nav>

            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="cart-table-container">
                            <table class="table table-cart">
                                <thead>
                                    <tr>
                                        <th class="product-col fs-3 fw-bold">المنتج</th>
                                        <th class="price-col fs-3 fw-bold">السعر</th>
                                        <th class="qty-col fs-3 fw-bold">العدد</th>
                                        <th class="fs-3 fw-bold">المجموع</th>
                                        <th class="fs-3 fw-bold text-success"> التوفير</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    {% for obj in object.items.all %}
                                    <tr class="product-row">
                                        <td class="product-col">
                                            <figure class="product-image-container">
                                                <a href="{% url 'Product:productDetail' obj.item.slug%}" class="product-image">
                                                    <img src="{{ obj.item.ProImg_1.url }}" alt="product">
                                                </a>
                                            </figure>
                                            <h2 class="product-title">
                                                <a href="{% url 'Product:productDetail' obj.item.slug%}" class="fw-bold">{{ obj.item.ProName }}</a>
                                            </h2>
                                        </td>
                                        <td class="fw-bold p-0"><p class="d-inline-block fs-4 ">ج م</p>{{ obj.item.ProPrice }} </td>
                                        <td class="fw-bold"><a href="{% url 'Product:remove_signal_item_from_cart' obj.item.slug %}"><i class="fas fa-minus"></i></a> {{obj.quantity}} <a href="{% url 'Product:add_to_cart' obj.item.slug %}"><i class="fas fa-plus"></i></a></td>
                                        {% if obj.item.ProDiscountPrice %}
                                            <td class="fw-bold p-0"><p class="d-inline-block fs-4 ">ج م</p>{{ obj.totle_price_discount}}</td>
                                            <td class="text-success fw-bold p-0"><p class="d-inline-block fs-4 ">ج م</p>{{ obj.totle_saving_price}}</td>

                                        {% else %}
                                            <td class="fw-bold p-0"><p class="d-inline-block fs-4 ">ج م</p>{{ obj.totle_price}}</td>
                                        {% endif %}
                                    </tr>
                                    <tr class="product-action-row">
                                        <td colspan="5" class="clearfix">
                                            <div class="float-right">
                                                <a href="{% url 'Product:remove_from_cart' obj.item.slug %}" title="حذف المنتج" class="text-danger fas fa-trash-alt"><span class="sr-only">حذف</span></a>
                                            </div><!-- End .float-right -->
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td>سلتك فارعة</td>
                                    </tr>
                                    {% endfor %}                                   
                                    
                                </tbody>

                                <tfoot>
                                    <tr>
                                        <td colspan="5" class="clearfix">
                                            <div class="float-right">
                                                <a href="{% url 'Product:products'%}" class="btn btn-outline-secondary fs-3 fw-bold">استمرار التسوق</a>
                                            </div><!-- End .float-left -->
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div><!-- End .cart-table-container -->

                        
                    </div><!-- End .col-lg-8 -->

                    <div class="col-lg-4">
                        <div class="cart-summary">
                            <h3 class="fs-1 fw-bold text-center">مراجعة طلبك </h3>
                            <table class="table table-totals">
                                <tbody>
                                    <tr>
                                        <td class="fs-3 fw-bold text-success"><p class="d-inline-block fs-4 ">ج م</p>{{object.get_total_saving}}</td>
                                        <td class="fs-3 fw-bold text-success">اجمالي التوفير</td>
                                    </tr>
                                    <tr>
                                        <td class="fs-3 fw-bold">سوف يتم حسابه</td>
                                        <td class="fs-3 fw-bold">تكاليف الشحن</td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td class="fs-3 fw-bold "><p class="d-inline-block fs-4 ">ج م</p>{{object.get_total}}</td>
                                        <td class="fs-3 fw-bold ">المجموع الكلي</td>
                                    </tr>
                                </tfoot>
                            </table>

                            <div class="checkout-methods">
                                <a href="checkout-shipping-2.html" class="btn btn-block btn-sm btn-primary fs-1 fw-bold">متابعة عملية الشراء</a>
                                <!-- <a href="#" class="btn btn-link btn-block">Check Out with Multiple Addresses</a> -->
                            </div><!-- End .checkout-methods -->
                        </div><!-- End .cart-summary -->
                    </div><!-- End .col-lg-4 -->
                </div><!-- End .row -->
            </div><!-- End .container -->
        </main><!-- End .main -->
{% endblock body %}

product/templates/product/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<main class="main">
            <nav aria-label="breadcrumb" class="breadcrumb-nav">
                <div class="container">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html" class="fs-3 fw-bold">الرئيسية</a></li> .
                        <li class="breadcrumb-item fs-3 fw-bold active" aria-current="page">المنتج</li>
                    </ol>
                </div>
            </nav>
            <div class="container">
                <div class="product-single-container product-single-grid">
                    <div class="row">
                        <div class="col-md-5 text-end">
                            <div class="product-single-details ">
                                <h1 class="product-title pb-1 fs-1 ">{{object}}</h1>
                                <div class="category-wrap pb-4">
                                    <div class="category-list">
                                        <a href="category.html" class="product-category  fs-5 fw-bold">{{object.get_category_dsplay}}</a>
                                    </div>
                                </div>
                                <!--<div class="ratings-container">
                                    <div class="product-ratings">
                                        <span class="ratings" style="width:60%"></span>
                                    </div>

                                    <a href="#" class="rating-link">( 6 Reviews )</a>
                                </div>--><!-- End .product-container -->
                                {% if object.ProStock == True %}
                                <div class="price-box">
                                    {% if product.ProDiscountPrice %}
                                            <span class="old-price fs-2"><p class="d-inline-block fs-4 ">ج م</p>{{product.ProPrice}}</span>
                                            <span class="product-price"><p class="d-inline-block fs-4 ">ج م</p>{{product.ProDiscountPrice}}</span>
                                        {% else %}
                                            <span class="product-price"><p class="d-inline-block fs-4 ">ج م</p>{{product.ProPrice}}</span>
                                        {% endif %}
                                </div><!-- End .price-box -->
                                {% else %}
                                <ul class="single-info-list fs-3 fw-bold">
                                    <li><strong class="text-danger fs-4">نفذت كمية المخزون</strong></li>
                                </ul>
                                {% endif %}

                                <div class="product-action" style="display: block;">
                                    <a href="{{object.get_add_to_cart_url}}" class="paction add-cart fs-1 fw-bold " id="success" onclick="click();" title="أضفه الي سلتك">
                                        أضافه للسلة
                                    </a>
                                    <a href="{{object.get_remove_from_cart_url}}" class="paction add-cart fs-1 fw-bold " id="success" onclick="click();" title="مسح من السلة">
                                        مسح من السلة
                                    </a>
                                    
                                </div><!-- End .product-action -->
                                
                            </div><!-- End .product-single-details -->
                        </div><!-- End .col-md-4 -->
                        <div class="col-md-7">
                            <div class="product-single-gallery popup-gallery">
                                <div class="row">
                                    <div class="col-6 product-item">
                                        <div class="inner">
                                            <img src="{{object.ProImg_1.url}}" data-zoom-image="{{object.ProImg_1.url}}" alt="product name">
                                            <span class="prod-full-screen">
                                                <i class="icon-plus"></i>
                                            </span>
                                        </div>
                                    </div><!-- End .col-6 -->
                                    <div class="col-6 product-item">
                                        <div class="inner">
                                            <img src="{{object.ProImg_2.url}}" data-zoom-image="{{object.ProImg_2.url}}" alt="product name">
                                            <span class="prod-full-screen">
                                                <i class="icon-plus"></i>
                                            </span>
                                        </div>
                                    </div><!-- End .col-6 -->
                                </div><!-- End .row -->
                            </div><!-- End .product-single-gallery -->
                        </div><!-- End .col-md-8 -->

                        
                    </div><!-- End .row -->
                </div><!-- End .product-single-container -->
                <!-- {% for Alter in allAlter %}
                  <h1>{{Alter}}</h1>
                {% endfor %} -->
                <!-- {{allAlter}} -->
                <div class="product-single-tabs text-end">

                    <ul class="nav nav-tabs float-end" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link fs-3 fw-bold" id="product-tab-desc" data-toggle="tab" href="#product-desc-content" role="tab" aria-controls="product-desc-content" aria-selected="false">مواصفات</a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                    <div class="tab-content">
                        <div class="tab-pane fade" id="product-desc-content" role="tabpanel" aria-labelledby="product-tab-desc">
                            <div class="product-desc-content">
                                <p class="text-danger">{{object.ProDesc|safe}}</p>
                            </div><!-- End .product-desc-content -->
                        </div><!-- End .tab-pane -->
                    </div><!-- End .tab-content -->
                </div><!-- End .product-single-tabs -->
            </div><!-- End .container -->
            
            <!-- <div class="with-border-top">
                <section class="container product-panel">
                    <div class="section-title">
                        <h2>منتجات مشابها</h2>
                    </div>
                    <div class="owl-carousel owl-theme" data-toggle="owl" data-owl-options="{
                        'margin': 4,
                        'items': 2,
                        'autoplayTimeout': 5000,
                        'dots': false,
                        'nav' : false,
                        'responsive': {
                            '768': {
                                'items': 3
                            },
                            '992' : {
                                'items' : 4
                            },
                            '1200': {
                                'items': 5
                            }
                        }
                    }">

                    
                        <div class="product-default inner-quickview inner-icon center-details">
                            <figure>
                                <a href="product-grid-layout.html">
                                    <img src="{% static 'assets/images/products/grey/la-germania-freestanding-cooker-90-x-60-cm-5-gas-burners-in-stainless.jpg' %}">
                                </a>
                                <a href="product-grid-layout.html" class="btn-view fs-3 fw-bold" title="لتفاصيل اكتر">لتفاصيل اكتر</a> 
                            </figure>
                            <div class="product-details">
                                <div class="category-wrap">
                                    <div class="category-list">
                                        <a href="category-sidebar-right.html" class="product-category">category</a>
                                    </div>
                                </div>
                                <h2 class="product-title">
                                    <a href="product-grid-layout.html">Product Short Name</a>
                                </h2>
                                <div class="price-box">
                                    <span class="old-price">$59.00</span>
                                    <span class="product-price">$49.00</span>
                                </div>
                            </div>
                        </div>
                    

                    </div>
                </section>
            </div> -->

</main><!-- End .main -->
<script>  
    $(document).on("click", "#success", function(e){
        swal('تم إرسال البيانات وهيتم التواصل مع حضرتك','شكرا','success')
    });
</script>
{% endblock body %}